### ISSUE TITLE
Cannot find the paper everywhere

### ISSUE THREAD

**Issue by Starboy-at-earth** [luzhangada/code-for-WCS-Net#1]
Could you please share the availble link of this paper?

**Comment by luzhangada** [comment]
Thanks for your interest, you can find in
https://drive.google.com/file/d/1q6bDBn_zSoEtdlEPjHL1v1egC9CcViL1/view?usp=sharing

Starboy-at-earth <notifications@github.com> 于2020年10月31日周六 上午10:26写道：
